# version: "3.8"

services:
  # سرویس دیتابیس PostgreSQL
  postgres_db:
    image: postgres:15-alpine
    container_name: user_profile_db
    restart: always
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: user_profile_main
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U your_db_user -d user_profile_main"]
      interval: 10s
      timeout: 5s
      retries: 5

  # سرویس Redis برای صف و Rate Limiting
  redis_cache:
    image: redis:7-alpine
    container_name: user_profile_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
